full_adderS <= ( ( ( ( full_adderA and ( not full_adderB ) ) or ( ( not full_adderA ) and full_adderB ) ) and ( not full_adderCin ) ) or ( ( not ( ( full_adderA and ( not full_adderB ) ) or ( ( not full_adderA ) and full_adderB ) ) ) and full_adderCin ) );
full_adderCout <= ( ( ( ( full_adderA and ( not full_adderB ) ) or ( ( not full_adderA ) and full_adderB ) ) and full_adderCin ) or ( full_adderA and full_adderB ) );
half_adderS <= ( not ( half_adderA or half_adderB ) );
half_adderC <= ( half_adderA and half_adderB );
four_bit_ripple_carry_adderV <= ( ( four_bit_ripple_carry_adderc3 and ( not four_bit_ripple_carry_adderc4 ) ) or ( ( not four_bit_ripple_carry_adderc3 ) and four_bit_ripple_carry_adderc4 ) );
four_bit_ripple_carry_adderCout <= four_bit_ripple_carry_adderc4;
four_bit_ripple_carry_addersum0 <= ( ( ( ( four_bit_ripple_carry_addera0 and ( not four_bit_ripple_carry_adderb0 ) ) or ( ( not four_bit_ripple_carry_addera0 ) and four_bit_ripple_carry_adderb0 ) ) and ( not four_bit_ripple_carry_adderCin ) ) or ( ( not ( ( four_bit_ripple_carry_addera0 and ( not four_bit_ripple_carry_adderb0 ) ) or ( ( not four_bit_ripple_carry_addera0 ) and four_bit_ripple_carry_adderb0 ) ) ) and four_bit_ripple_carry_adderCin ) );
four_bit_ripple_carry_adderc1 <= ( ( ( ( four_bit_ripple_carry_addera0 and ( not four_bit_ripple_carry_adderb0 ) ) or ( ( not four_bit_ripple_carry_addera0 ) and four_bit_ripple_carry_adderb0 ) ) and four_bit_ripple_carry_adderCin ) or ( four_bit_ripple_carry_addera0 and four_bit_ripple_carry_adderb0 ) );
four_bit_ripple_carry_addersum1 <= ( ( ( ( four_bit_ripple_carry_addera1 and ( not four_bit_ripple_carry_adderb1 ) ) or ( ( not four_bit_ripple_carry_addera1 ) and four_bit_ripple_carry_adderb1 ) ) and ( not four_bit_ripple_carry_adderc1 ) ) or ( ( not ( ( four_bit_ripple_carry_addera1 and ( not four_bit_ripple_carry_adderb1 ) ) or ( ( not four_bit_ripple_carry_addera1 ) and four_bit_ripple_carry_adderb1 ) ) ) and four_bit_ripple_carry_adderc1 ) );
four_bit_ripple_carry_adderc2 <= ( ( ( ( four_bit_ripple_carry_addera1 and ( not four_bit_ripple_carry_adderb1 ) ) or ( ( not four_bit_ripple_carry_addera1 ) and four_bit_ripple_carry_adderb1 ) ) and four_bit_ripple_carry_adderc1 ) or ( four_bit_ripple_carry_addera1 and four_bit_ripple_carry_adderb1 ) );
four_bit_ripple_carry_addersum2 <= ( ( ( ( four_bit_ripple_carry_addera2 and ( not four_bit_ripple_carry_adderb2 ) ) or ( ( not four_bit_ripple_carry_addera2 ) and four_bit_ripple_carry_adderb2 ) ) and ( not four_bit_ripple_carry_adderc2 ) ) or ( ( not ( ( four_bit_ripple_carry_addera2 and ( not four_bit_ripple_carry_adderb2 ) ) or ( ( not four_bit_ripple_carry_addera2 ) and four_bit_ripple_carry_adderb2 ) ) ) and four_bit_ripple_carry_adderc2 ) );
four_bit_ripple_carry_adderc3 <= ( ( ( ( four_bit_ripple_carry_addera2 and ( not four_bit_ripple_carry_adderb2 ) ) or ( ( not four_bit_ripple_carry_addera2 ) and four_bit_ripple_carry_adderb2 ) ) and four_bit_ripple_carry_adderc2 ) or ( four_bit_ripple_carry_addera2 and four_bit_ripple_carry_adderb2 ) );
four_bit_ripple_carry_addersum3 <= ( ( ( ( four_bit_ripple_carry_addera3 and ( not four_bit_ripple_carry_adderb3 ) ) or ( ( not four_bit_ripple_carry_addera3 ) and four_bit_ripple_carry_adderb3 ) ) and ( not four_bit_ripple_carry_adderc3 ) ) or ( ( not ( ( four_bit_ripple_carry_addera3 and ( not four_bit_ripple_carry_adderb3 ) ) or ( ( not four_bit_ripple_carry_addera3 ) and four_bit_ripple_carry_adderb3 ) ) ) and four_bit_ripple_carry_adderc3 ) );
four_bit_ripple_carry_adderc4 <= ( ( ( ( four_bit_ripple_carry_addera3 and ( not four_bit_ripple_carry_adderb3 ) ) or ( ( not four_bit_ripple_carry_addera3 ) and four_bit_ripple_carry_adderb3 ) ) and four_bit_ripple_carry_adderc3 ) or ( four_bit_ripple_carry_addera3 and four_bit_ripple_carry_adderb3 ) );

